sudo: required
os: linux
dist: trusty
language: php
php:
  - '7.0'

env:
  global:
    - PROJECT_NAME=104jbcp-slim-test
    - DEPLOY_BUCKET_BASE_NAME=jtravis-codedeploy

before_install:
  # install awscli
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  # start web server
  - php -S 0.0.0.0:8080 -t public&

before_script:
  - composer config -g github-oauth.github.com ${GITHUB_ACCESS_TOKEN}
  - composer install

script:
  # run testing
  - php vendor/bin/phpcs
  - php vendor/bin/codecept run -f

notifications:
  email:
    recipients:
      - jacky.lin@104.com.tw
    on_success: always
    on_failure: always

cache:
  directories:
    - vendor

after_success:
  # export AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY by TRAVIS_BRANCH, default: dev
  - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - export DEPLOY_BUCKET_NAME=${DEPLOY_BUCKET_BASE_NAME}
  - export DEPLOYMENT_TAG="dev"

  # echo aws info
  - echo "AWS_ACCESS_KEY_ID:" ${AWS_ACCESS_KEY_ID}

  # echo tag info
  - echo "DEPLOYMENT_TAG:" ${DEPLOYMENT_TAG}
  - echo "DEPLOY_BUCKET_NAME:" ${DEPLOY_BUCKET_NAME}

  # generate swagger.yaml
  - make swagger

before_deploy:
  - composer install --no-dev --optimize-autoloader
  - zip -r latest route app bootstrap config public routes scripts vendor .env .appspec.yml
  - test -d myCodeDeploy || mkdir myCodeDeploy
  - mv latest.zip myCodeDeploy/latest.zip
  - aws s3 cp myCodeDeploy/latest.zip s3://jtravis-codedeploy

deploy:
  # dev
  - provider: s3
    access_key_id: &aws_access_key ${AWS_ACCESS_KEY_ID}
    secret_access_key: &aws_secret_key ${AWS_SECRET_ACCESS_KEY}
    bucket: ${DEPLOY_BUCKET_NAME}
    local_dir: myCodeDeploy
    skip_cleanup: true
    region: &region ap-southeast-1
    on:
      branch: master

  - provider: codedeploy
    access_key_id: &aws_access_key ${AWS_ACCESS_KEY_ID}
    secret_access_key: &aws_secret_key ${AWS_SECRET_ACCESS_KEY}
    bucket: ${DEPLOY_BUCKET_NAME}
    key: latest.zip
    application: "jtravis"
    deployment_group: gdeploy
    region: ap-southeast-1
    on:
      branch: master