sudo: required
os: linux
dist: trusty
language: php
php:
  - '7.0'

env:
  global:
    - PROJECT_NAME=104jbcp-slim-test

before_install:
  # start web server
  - php -S 0.0.0.0:8080 -t public&

before_script:
  - composer config -g github-oauth.github.com ${GITHUB_ACCESS_TOKEN}
  - composer install

script:
  # run testing
  - php vendor/bin/phpcs
  - php vendor/bin/codecept run -f

notifications:
  email:
    recipients:
      - jacky.lin@104.com.tw
    on_success: always
    on_failure: always
