version: 0.1
os: linux
files:
  - source: /
    destination:  /var/www/htdocs/jobs/slim/
hooks:
  BeforeInstall:
    - location: scripts/codedeploy/beforeInstall.sh
      timeout: 150
      runas: root
  AfterInstall:
    - location: scripts/codedeploy/afterInstall.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/codedeploy/start.sh
      timeout: 60
      runas: root